package com.nerdscorner.android.plugin.utils

object Strings {

    const val OAUTH_TOKEN_PROPERTY = "oauth_token_property"
    const val ORGANIZATION_NAMES_PROPERTY = "organization_name_property"
    const val TRAVIS_CI_TOKEN_PROPERTY = "travis_ci_property"
    const val CIRCLE_CI_TOKEN_PROPERTY = "circle_ci_property"
    const val SHOW_REPOS_FROM_ORGANIZATION_ONLY = "show_repos_from_organizations_only"
    const val SHOW_DEPLOYMENT_PANEL = "show_deployment_panel"

    const val HASH_POUND = "#"
    const val BLANK = ""
    const val NAME = "Name"
    const val TITLE = "Title"
    const val DATE = "Date"
    const val STATUS = "Status"
    const val PR_STATUS = "PR status"
    const val BUILD_STATUS = "Build status"
    const val TAG = "Tag"
    const val CI_ACTIONS = "CI Actions"
    const val AUTHOR = "Author"
    const val DATE_FORMAT = "dd/MM/yyyy"
    const val EMPTY_LIST = "[]"
    const val LOGIN_ERROR = "Login error"
    const val CHANGELOG = "Libraries changelog"
    const val EMPTY_OAUTH_TOKEN = "The OAuth Token cannot be empty"
    const val EMPTY_ORGANIZATION_NAME = "The organization's name cannot be empty"
    const val VERIFY_OAUTH_TOKEN = "Verify your organization's name, your OAuth Token and its permissions"
    const val LOGGED_AS = "Logged in as %s (%s)"
    const val ENTER_CIRCLE_CI_TOKEN = "Enter CircleCI API Token"
    const val ENTER_TRAVIS_CI_TOKEN = "Enter Travis CI API Token"
    const val VERSION = "Version"
    const val RELEASES = "Releases"
    const val PULL_REQUEST = "Pull Request"
    const val VERSION_BUMPS = "Version Bumps"
    const val PREVIOUS_VERSION = "Previous Version"
    const val NEXT_VERSION = "Next Version"
    const val ERROR_DETAILS = "Error details"
}
